/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bither_util_Test */


#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jstring JNICALL Java_org_huihui_piccompress_net_bither_util_NativeUtil_compressBitmap(JNIEnv*,
		jclass, jobject , int , int , int ,
		jbyteArray , jboolean );

#ifdef __cplusplus
}
#endif

